### ISSUE TITLE
Display intel compiler versions used with R versions, and add new R 3.5 + Intel 18 version

### ISSUE THREAD

**Issue by ericfranz** [OSC/bc_osc_rstudio_server#14]
1. Add new option for R 3.5.0 with Intel 18.0.3 compiler. For this one the modules can be "intel/18.0.3 R/3.5.0 rstudio/1.1.380_server" without overloading using the colon
2. For all R versions, the display name should include the intel compiler used i.e.

- 3.5.0 (with intel/18.0.3 compiler)
- 3.5.0 (with intel/16.0.3 compiler)
- 3.4.2 (with intel/16.0.3 compiler)
- 3.3.2 (with intel/16.0.3 compiler)

**Comment by ericfranz** [comment]
This is safe to do after the software refresh next Tuesday.

**Comment by MorganRodgers** [comment]
I just tried this and the command `module load intel/18.0.3 R/3.5.0 rstudio/1.1.380_server` throws the following error:

```
Lmod has detected the following error: Cannot load module
"rstudio/1.1.380_server" without these module(s) loaded:
   R/3.4.2

While processing the following module(s):
    Module fullname         Module Filename
    ---------------         ---------------
    rstudio/1.1.380_server  /usr/local/share/lmodfiles/Core/rstudio/1.1.380_server.lua
```
