### ISSUE TITLE
Fail to deploy because of proot

### ISSUE THREAD

**Issue by nickjer** [OSC/bc_osc_rstudio_server#4]
Unable to deploy a fresh copy of this app due to:

```
wget http://static.proot.met/proot-x86 -P /users/appl/jnicklas/awesim/dev/bc_osc_rstudio_server/template/bin
--2017-04-21 16:22:05--  http://static.proot.met/proot-x86
Resolving static.proot.met... failed: Name or service not known.
```

**Comment by ericfranz** [comment]
Options:

- fork proot github repo, follow build from source directions, use that version
- embed proot binary in repo with app, change license of app from MIT to same license as bc_osc_rstudio_server
- store proot binary in separate repo, expose as bower package, and include in app that needs it

Of course I'm nervous about this dependency. What happens if we no longer can use this in the future? One option is we get a "start rstudio" script that users can run as sudo and it uses chroot etc.

**Comment by nickjer** [comment]
I feel the best option is to make it a requirement much like R and RStudio Server are and have the Scientific Applications team install it on the cluster that this app runs on.

**Comment by nickjer** [comment]
Another option with no dependencies is to propose to systems a batch job flag (similar to `:vis`) or setting it as default that will set up a mount namespace through `unshare -m` and then `mount --bind` for `/tmp` and `/var/tmp` in a `root` run prologue script.

This would mimic what is done in systemd with the `PrivateTmp` option.

Each batch script would have its own namespaced (private) `/tmp` and `/var/tmp` directories.

**Comment by nickjer** [comment]
Ticket opened with OSC Sci Apps to install proot on Owens:

https://oarnet.service-now.com/nav_to.do?uri=incident.do?sys_id=9d14a94e13d23640804831f18144b034

**Comment by ericfranz** [comment]
Lets also fork the GitHub project containing the release version that the install. Just in case it disappears for some reason and we need to revisit.

**Comment by brianmcmichael** [comment]
IT's going to be weeks before PRoot is installed on the system per [INC0315329](https://oarnet.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=9d14a94e13d23640804831f18144b034%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true), and at that point this dependency is out of our control.

I've forked the PRoot repo and added the static binaries at https://github.com/OSC/PRoot/tree/master/bin

The script to download these had been preemptively removed at https://github.com/OSC/bc_osc_rstudio_server/commit/2f7b7f2cd6690f01520d3ff364405a80533939bb#diff-e819e5862cd96ed3ddf3eed683f5f0ad and should be restored and the links updated to use the github paths.

**Comment by basilgohar** [comment]
@nickjer What do you think the relative complexity of having systems do 
this would be?  Do you think they'll balk at the idea?

**Comment by brianmcmichael** [comment]
@basilgohar see [INC0315329](https://oarnet.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=9d14a94e13d23640804831f18144b034%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)

**Comment by nickjer** [comment]
@basilgohar: I never compiled it so I don't know.

**Comment by nickjer** [comment]
This is resolved with:

fad2b1a
